---
- name: Create users 
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: present
    shell: /bin/bash

- name: Set authorized keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_pubkey }}"

- name: Allow sudo for administrator
  copy:
    content: '{{ item.name }} ALL=(ALL:ALL) NOPASSWD: ALL'
    dest: '/etc/sudoers.d/{{ item.name }}'

- name: Create alias file
  template:
    src: bash_aliases.j2
    dest: '/home/{{ item.name }}/.bash_aliases'
    owner: '{{ item.name }}'
    group: '{{ item.name }}'
    mode: '0644'
