---
- name: Add Caddy GPG
  apt_key:
   url: "{{ caddy_apt_gpg_key }}"
   state: present
  become: true

- name: Add Caddy Repo
  apt_repository:
    repo: "{{ caddy_apt_repository }}"
    state: present
  become: true

- name: Install Caddy
  apt:
    name: '{{ caddy_package }}'
    state: present
    update_cache: true
  become: true

- name: Install XCaddy
  command: 'go install {{ xcaddy_repo }}'
  environment:
    PATH: '{{ path }}'
    GOPATH: '{{ user_dir }}/go'

- name: Use XCaddy to build Caddy with custom plugins
  become: true
  command: "xcaddy build --with {{ item }}"
  with_items: '{{ xcaddy_custom_build }}'
  environment:
    PATH: '{{ path }}'
    GOPATH: '{{ user_dir }}/go'
  
- name: Move Xcaddy to /usr/bin/
  copy:
    src: "caddy"
    dest: /usr/bin/caddy
    remote_src: yes

- name: Open Caddy port
  ufw:
    rule: allow
    port: 80,443
    proto: tcp

- name: Make Caddy dir
  file:
    path: '/etc/caddy/'
    state: directory

- name: Create Caddyfile
  template:
    src: Caddyfile
    dest: '/etc/caddy/Caddyfile'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0644'

- name: Start Caddy service
  systemd:
    name: caddy
    daemon_reload: yes
    enabled: yes
