---
- name: Install essentials
  become: true
  apt:
    name:
      - net-tools
      - ncdu
      - vnstat
      - tree
      - htop
      - zip
      - unzip
      - git
      - ufw
      - bash-completion
      - lz4
      - lsof
      - make
      - build-essential
      - gcc
      - git
      - jq
      - chrony
      - html2text
    state: latest
    update_cache: true

- name: Download go
  get_url:
    url: 'https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz'
    dest: '/tmp/go{{ go_version }}.linux-amd64.tar.gz'
    mode: '0700'

- name: Unarchive go
  unarchive:
    src: '/tmp/go{{ go_version }}.linux-amd64.tar.gz'
    remote_src: yes
    dest: '/usr/local/'
    owner: root
    group: root
    mode: '0755'

- name: Change go folder permission
  file:
    path: '{{ user_dir }}/go'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    recurse: true
    mode: '0755'

- name: Copy .profile
  template:
    src: 'profile.j2'
    dest: '{{ user_dir }}/.profile'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0600'
