# xcaddy: https://github.com/caddyserver/xcaddy#install
---
- name: change ansible_host to caddy server
  set_fact:
    host_ip: '{{ ansible_host }}'
    ansible_host: '{{ caddy_server }}'

- name: Add Caddy GPG
  apt_key:
   url: "{{ caddy_apt_gpg_key }}"
   state: present
  become: true

- name: Add Caddy Repo
  apt_repository:
    repo: "{{ caddy_apt_repository }}"
    state: present
  become: true

- name: Install Caddy
  apt:
    name: '{{ caddy_package }}'
    state: present
    update_cache: true
  become: true

- name: Install XCaddy
  command: 'go install {{ xcaddy_repo }}'
  environment:
    PATH: '{{ path }}'
    GOPATH: '{{ user_dir }}/go'

- name: Use XCaddy to build Caddy with custom plugins
  become: true
  command: "xcaddy build --with github.com/caddyserver/transform-encoder --with github.com/RussellLuo/caddy-ext/ratelimit"
  environment:
    PATH: '{{ path }}'
    GOPATH: '{{ user_dir }}/go'
  
- name: Move Xcaddy to /usr/bin/
  copy:
    src: "caddy"
    dest: /usr/bin/caddy
    remote_src: yes

- name: Open Caddy port
  ufw:
    rule: allow
    port: 80,443
    proto: tcp

- name: Make Caddy dir
  file:
    path: '/etc/caddy/'
    state: directory

- name: Make rest dir
  file:
    path: '/etc/caddy/rest'
    state: directory

- name: Make rpc dir
  file:
    path: '/etc/caddy/rpc'
    state: directory

- name: Make grpc dir
  file:
    path: '/etc/caddy/grpc'
    state: directory

- name: Create Caddyfile
  template:
    src: Caddyfile
    dest: '/etc/caddy/Caddyfile'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0644'
  tags: caddyfile

- name: Create rest file
  template:
    src: rest.caddy
    dest: '/etc/caddy/rest.caddy'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0644'
  tags: caddyfile

- name: Create rpc file
  template:
    src: rpc.caddy
    dest: '/etc/caddy/rpc.caddy'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0644'
  tags: caddyfile

- name: increase buffersize
  command: 'sudo sysctl -w net.core.rmem_max=2500000'

- name: Make sure RuntimeMaxSec in 'caddy.service' exists
  lineinfile:
    path: '{{ service_path }}'
    insertafter: '^TimeoutStopSec=5s'
    line: 'RuntimeMaxSec=7200'
    state: present

- name: Make sure Restart=always in 'caddy.service' exists
  lineinfile:
    path: '{{ service_path }}'
    insertafter: '^TimeoutStopSec=5s'
    line: 'Restart=always'
    state: present

- name: Make sure caddy.service is started and enabled via systemd
  systemd:
    name: "caddy.service"
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: switch back to original ip
  set_fact:
    ansible_host: '{{ host_ip }}'
