---
- name: Create users
  include_tasks: create_users.yml
  loop: "{{ user_details }}"

- name: Configure Machine
  import_tasks: configure_machine.yml

- name: Update machine
  import_tasks: update_machine.yml

- name: Install essentials
  import_tasks: install_essentials.yml

- name: Install node exporter
  import_tasks: install_node_exporter.yml
  when: node_exporter|default(false)|bool == true

- name: Install promtail
  import_tasks: install_promtail.yml
  when: promtail|default(false)|bool == true

- name: Set CPU governor
  import_tasks: performance.yml

- name: Install Zabbix
  import_tasks: install_zabbix.yml

- name: Setup Swap
  import_tasks: setup_swap.yml

- name: Install Caddy
  import_tasks: install_caddy.yml
  when: caddy|default(false)|bool == true
