---
- name: Check if cpufrequtils agent file exists
  stat:
    path: /etc/default/cpufrequtils
  register: cpu_governor_check

- name: Install and setup cpufrequtils
  when: not cpu_governor_check.stat.exists
  become: true
  block:
    - name: Install cpufrequtils
      apt:
        name: cpufrequtils
        state: latest
        update_cache: true

    - name: Set cpufrequtils params
      shell:
        cmd: |
          cat > /etc/default/cpufrequtils << EOF
          ENABLE="true"
          GOVERNOR="performance"
          EOF

    - name: Start cpufrequtils
      systemd:
        name: cpufrequtils
        state: started
        daemon_reload: true
        enabled: true
      changed_when: false

- name: Set journald to use RAM
  become: true
  shell:
    cmd: |
      cat > /etc/systemd/journald.conf << EOF
      [Journal]
      Storage=volatile
      RuntimeMaxFileSize=256M
      RuntimeMaxFiles=5
      ForwardToSyslog=no
      EOF

- name: restart journald
  systemd:
    name: systemd-journald
    state: restarted
    daemon_reload: true
    enabled: true
