---
- name: Install essentials
  become: true
  apt:
    name:
      - awscli
      - snapd
    state: latest
    update_cache: true

- name: Configure AWS
  shell: aws configure set {{ item.key }} {{ item.value }}
  no_log: True
  with_dict:
    aws_access_key_id: "{{ aws_access_key }}"
    aws_secret_access_key: "{{ aws_secret_key }}"
  become_user: "{{ ansible_user }}"

- name: Configure AWS max bandwidth
  shell: aws configure set default.s3.max_bandwidth 60MB/s
  become_user: "{{ ansible_user }}"
